version: '3.8'

networks:
  frontend:
  backend:

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - frontend
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - postgres-db

  # in practice these details should be hidden in .env files
  postgres-db:
    container_name: postgres-db
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: TerraHealers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: T3rraHealers
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

# for data persistence
volumes:
  postgres-db: